<?php
  
  /*
  * Implements hook_install.
  */
  function  hitsa_areas_of_study_install(){
        //////////////////Defineerime muutujad//////////////////////////////////////////////
        $voc_name = 'class_group';
        $voc_label = st('Class/Group');
        $site_default_language = language_default();
        //////////////////Loome sisutüübid/////////////////////////////////////////////////
        
        $types = array(
            array(
            'type' => 'field_of_study',
            'name' => st('Area of study'),
            'base' => 'node_content',
            'description' => st("One calendar event"),
            'default_language' => $site_default_language->language,
            'custom' => 1,
            'modified' => 1,
            'locked' => 0,
            ),
         );
    
         foreach ($types as $type) {
              $type = node_type_set_defaults($type);
              node_type_save($type);
            //   node_add_body_field($type);
         }
        //////////////////Kontrollime kas sõnastik eksisteerib//////////////////////////////
        
        $vocab = taxonomy_vocabulary_machine_name_load($voc_name);
        if (empty($vocab)) {
            ////////////////Kui ei eksisteeri loome uue sõnastiku
            $new_taxonomy = (object) array(
                'name' => $voc_label,
                'description' => st('Here are different classes and groups'),
                'machine_name' => $voc_name,
                'language' => 'und',
                'i18n_mode' => 4,
                'rdf_mapping' => array(
                  'rdftype' => array(
                    0 => 'skos:ConceptScheme',
                  ),
                  'name' => array(
                    'predicates' => array(
                      0 => 'dc:title',
                    ),
                  ),
                  'description' => array(
                    'predicates' => array(
                      0 => 'rdfs:comment',
                    ),
                  ),
                ),
            );  
            taxonomy_vocabulary_save($new_taxonomy);  
        } 
        hitsa_areas_of_study_create_fields($voc_name);
  }

  
    /**
     * hook_uninstall
    */
    function hitsa_areas_of_study_uninstall() {
        ///Defineerime muutujad
        $voc_name = 'class_group';
        ///Laeme s6nastiku
        $vocab = taxonomy_vocabulary_machine_name_load($voc_name);
        $vid = $vocab->vid;
        ////Kustutame sonastiku
        taxonomy_vocabulary_delete($vid);
        
        ////Kustutame loodud valjad
        $instances = field_info_instances('taxonomy_term', $voc_name);
        foreach ($instances as $instance) {
            field_delete_instance($instance);
        }
        
        $content_type = 'field_of_study';
        $sql = db_select('node', 'n');
        $sql -> condition('n.type', $content_type, '=');
        $sql -> fields('n');
        $result = $sql->execute();
        $nids = array();
        foreach ($result as $row) {
            $nids[] = $row->nid;
        }
        if (!empty($nids)){
            node_delete_multiple($nids);
        }
        //Kontrollime enne sisutyybu kustutamist, kas eksisteerib.
        if(node_type_load($content_type)){
            node_type_delete($content_type);
        }
        
        // find all fields and delete instance
        $instances = field_info_instances('node', $content_type);
        foreach ($instances as $instance_name => $instance) {
                field_delete_instance($instance);
        }
        //Kustutame tolke voimaluse
        variable_del('language_content_type_'.$cont_type);
    }