<?php

module_load_include('inc', 'hitsa_locations', 'includes/hitsa_locations.views');

/*
* Implements hook_node_info().
*/
function hitsa_locations_node_info() {
  return array(
    'contact_location' => array(
      'name' => t('Location'),
      'base' => 'contact_location',
      'description' => t('Location data.'),
      'has_title' => TRUE,
      'title_label' => t('Name'),
    ),
  );
}

/*
* Implements hook_form().
*/
function contact_location_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_node_view().
 */
function hitsa_locations_node_view($node, $view_mode, $langcode) {
  global $user;
  // Restrict access to logo node full page view.
  if ($view_mode == 'full' 
  && arg(0) == 'node' 
  && arg(1) == $node->nid
  && $node->type === 'location'
  && !user_access('administer content', $user)
  ) {
    // Redirect user to front page.
    drupal_goto();
  }
}