<?php

module_load_include('inc', 'hitsa_locations', 'includes/hitsa_locations.views');

/*
* Implements hook_node_info().
*/
function hitsa_locations_node_info() {
  return array(
    'contact_location' => array(
      'name' => t('Location'),
      'base' => 'contact_location',
      'description' => t('Location data.'),
      'has_title' => TRUE,
      'title_label' => t('Name'),
    ),
  );
}

function hitsa_locations_block_info() {
  $blocks['hitsa_locations'] = array(
    'info' => t('HITSA Locations'),
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'contact',
    'region' => 'sidebar_right',
    'status' => "1",
  );
  
  return $blocks;
}

function hitsa_locations_theme() {
  $items['locations_block'] = array(
    'template' => 'hitsa-locations-block',
    'path' => drupal_get_path('module', 'hitsa_locations') . '/templates',
    'variables' => array(
      'locations' => NULL,
    ),
  );
  return $items;
}

function hitsa_locations_block_content() {
  // Add location block data
  $locations = array();
  $nids_array = views_get_view_result('hitsa_locations', 'locations_sort');
  if(!empty($nids_array)) {
    $nids = array();
    foreach($nids_array as $n) {
      $nids[] = $n->nid;
    }
    $locations = node_load_multiple($nids);
    return theme('locations_block', array('locations' => $locations));
  } else {
    return '';
  }
}

function hitsa_locations_block_view($delta = '') {
  $output = array();
  switch($delta) {
    case 'hitsa_locations':
      $output = array('subject' => NULL, 'content' => hitsa_locations_block_content());
      break;
  }
  return $output;
}

/*
* Implements hook_form().
*/
function contact_location_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_node_view().
 */
function hitsa_locations_node_view($node, $view_mode, $langcode) {
  global $user;
  // Restrict access to logo node full page view.
  if ($view_mode == 'full' 
  && arg(0) == 'node' 
  && arg(1) == $node->nid
  && $node->type === 'location'
  && !user_access('administer content', $user)
  ) {
    // Redirect user to front page.
    drupal_goto();
  }
}