<?php

module_load_include('inc', 'hitsa_logos', 'includes/hitsa_logos.views');

function hitsa_logos_node_info() {
  return array(
    'logo' => array(
      'name' => t('Logo'),
      'base' => 'logo',
      'description' => t('Sponsor or award logo.'),
      'has_title' => TRUE,
      'title_label' => t('Name'),
    ),
  );
}

/**
 * Implements hook_block_info_alter()
 */
function hitsa_logos_block_info_alter(&$blocks, $theme, $code_blocks) {
  if(!empty($blocks['views']['hitsa_logos-awards_block']) && $theme === 'hitsa') {
    $blocks['views']['hitsa_logos-awards_block']['status'] = 1;
    $blocks['views']['hitsa_logos-awards_block']['region'] = 'sidebar_right';
    $blocks['views']['hitsa_logos-awards_block']['visibility'] = BLOCK_VISIBILITY_LISTED;
    $blocks['views']['hitsa_logos-awards_block']['pages'] = '<front>';
    $blocks['views']['hitsa_logos-awards_block']['weight'] = 100;
  }
}

/**
 * Implements hook_form()
 */
function logo_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_node_view().
 */
function hitsa_logos_node_view($node, $view_mode, $langcode) {
  global $user;
  // Restrict access to logo node full page view.
  if ($view_mode == 'full'
  && arg(0) == 'node'
  && arg(1) == $node->nid
  && $node->type === 'logo'
  && !user_access('administer content', $user)
  ) {
    // Redirect user to front page.
    drupal_goto();
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function hitsa_logos_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'hitsa_logos');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

function hitsa_logos_form_alter(&$form, &$form_state, $form_id) {

  if($form_id === 'views_form_hitsa_logos_awards_sort') {
    $form['title'] = array('#markup' => '<h2 style="margin-bottom:0px;">' . t('Awards') . '</h2>');
  }
  if($form_id === 'views_form_hitsa_logos_partners_sort') {
    $form['title'] = array('#markup' => '<h2 style="margin-bottom:0px;">' . t('Partners') . '</h2>');
  }
}
