<?php

module_load_include('inc', 'hitsa_articles', 'includes/hitsa_articles.views');
module_load_include('inc', 'hitsa_articles', 'includes/hitsa_articles.theme');

function hitsa_articles_menu() {
  $items['news'] = array(
    'title' => 'News',
    'page callback' => 'hitsa_articles_page_view',
    'page arguments' => array('news'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'hitsa-header-menu',
    'weight' => 0,
  );
  
  $items['our-stories'] = array(
    'title' => 'Our stories',
    'page callback' => 'hitsa_articles_page_view',
    'page arguments' => array('our_stories'),
    'access arguments' => array('access content'),
  );
  
  $items['api/articles'] = array(
    'title' => 'Articles API',
    'page callback' => 'hitsa_articles_filter',
    'access arguments' => array('access content'),
  );
  
  return $items;
}

function hitsa_articles_get_more_articles_block_nodes($variables) {
  $query = array();
  if(!empty($variables['article_type'][0]['value'])) {
    // Show standard news category block for important news.
    $query['article_type'] = $variables['article_type'][0]['value'] !== 'important' ? 
      $variables['article_type'][0]['value'] : 'news';
    
    // Exclude current node
    $query['nids_not_in'] = array($variables['nid']);
    
    // Query up to 6 nodes
    $query['range'] = array(0, 6);
    
    if($result = hitsa_articles_query_content($query)) {
      $articles_nids = !empty($result['content']) ? $result['content'] : NULL;
    }
    
    if(!empty($articles_nids['node'])) {
      $articles = node_load_multiple(array_keys($articles_nids['node']));
    }
  }
  return !empty($articles) ? $articles : array();
}

/**
 * Implements hook_node_info()
 */
function hitsa_articles_node_info() {
  return array(
    'article' => array(
      'name' => t('Article'),
      'base' => 'article',
      'description' => t('Use <em>articles</em> for time-sensitive content like news, press releases or blog posts.'),
      'has_title' => TRUE,
      'title_label' => t('Title'),
    ),
  );
}

function hitsa_articles_block_info() {
  $blocks['hitsa_our_stories'] = array(
    'info' => t('HITSA Our Stories'),
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '<front>',
    'region' => 'sidebar_right',
    'status' => "1",
  );
  
  $blocks['hitsa_important_article'] = array(
    'info' => t('HITSA Important article'),
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '<front>',
    'region' => 'super_news',
    'status' => "1",
  );
  
  return $blocks;
}

function hitsa_articles_block_view($delta = '') {
  $output = array();
  switch($delta) {
    case 'hitsa_our_stories':
      $query = array('article_type' => 'our_stories', 'range' => array(0, 2));
      if($result = hitsa_articles_query_content($query)) {
        $our_stories_nids = !empty($result['content']) ? $result['content'] : NULL;
      }
      
      if(!empty($our_stories_nids['node'])) {
        $our_stories_nodes = node_load_multiple(array_keys($our_stories_nids['node']));
        $authors = array();
        foreach($our_stories_nodes as $story_node) {
          $authors[$story_node->uid] = user_load($story_node->uid);
        }
        $content = theme('hitsa_our_stories_block', array('nodes' => $our_stories_nodes, 'authors' => $authors));
        $output = array('subject' => NULL, 'content' => $content);
      }
      break;
    case 'hitsa_important_article':
      // Add the "Important article" block
      $query = array('article_type' => 'important', 'range' => array(0, 1));
      if($result = hitsa_articles_query_content($query)) {
        $important_nid = !empty($result['content']) ? $result['content'] : NULL;
      }
      if(!empty($important_nid['node'])) {
        $article_nid = reset($important_nid['node']);
        $important_article = node_load($article_nid->nid);
        $content = theme('hitsa_important_article', array('node' => $important_article));
        $output = array('subject' => NULL, 'content' => $content);
      }
      break;
  }
  
  return $output;
}

function hitsa_articles_block_info_alter(&$blocks, $theme, $code_blocks) {
  if(!empty($blocks['views']['hitsa_news-news_block']) && $theme === 'hitsa') {
    $blocks['views']['hitsa_news-news_block']['status'] = 1;
    $blocks['views']['hitsa_news-news_block']['region'] = 'content';
    $blocks['views']['hitsa_news-news_block']['visibility'] = BLOCK_VISIBILITY_LISTED;
    $blocks['views']['hitsa_news-news_block']['pages'] = '<front>';
  }
}

/**
 * Implement hook_form()
 */
function article_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

function hitsa_articles_form_alter(&$form, &$form_state, $form_id) {
  if($form_id === 'article_node_form') {
    // Show summary by default.
    hitsa_core_formatted_text_show_summary();
    if(!empty($form['body'])) {
      $form['body'][LANGUAGE_NONE][0]['#required'] = TRUE;
      $form['body'][LANGUAGE_NONE][0]['summary']['#required'] = TRUE;
    }
  }
}

function hitsa_articles_filter() {
  global $language;
  
  $output = hitsa_articles_page_view('news', TRUE);
  
  print $output;
  exit;
}

function hitsa_articles_query_content($q = array(), $count = FALSE) {
  $query = new EntityFieldQuery();
  
  $parameters = _hitsa_articles_set_query_parameters($q);
  
  $query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', 'article')
  ->propertyCondition('status', NODE_PUBLISHED)
  ->propertyOrderBy('created', 'DESC');
  
  foreach($parameters as $parameter) {
    $query->{$parameter['type']}(...$parameter['arguments']);
  }

  $output = array();
  
  
  
  $output['content'] = $query->execute();
  
  if($count) {
    $output['count'] = $query->range(0, PHP_INT_MAX)->count()->execute();
  }

  return $output;
}

function _hitsa_articles_set_query_parameters($query = array()) {
  global $language;

  $parameters = array();
  
  // Language
  $parameters[] = array(
    'type' => 'propertyCondition',
    'arguments' => array('language', $language->language),
  );
  
  // Page / Range
  if(!empty($query['page'])) {
    $page_range = ($query['page'] - 1) * 12;

    $parameters[] = array(
      'type' => 'range',
      'arguments' => array($page_range, $page_range + 12),
    );
  } else if(!empty($query['range'])) {
    
    $parameters[] = array(
      'type' => 'range',
      'arguments' => array($query['range'][0], $query['range'][1]),
    );
  }
  
  // Pager
  if(!empty($query['pager'])) {
    $parameters[] = array(
      'type' => 'pager',
      'arguments' => array($query['pager']),
    );
  }
  
  // Academic year
  if(!empty($query['category'])) {
    $academic_years = explode(',', $query['category']);
    
    foreach($academic_years as $academic_year) {
      if($academic_year === 'all') {
        $academic_years = NULL;
        break;
      }
    }
    if(!empty($academic_years)) {
      $parameters[] = array(
        'type' => 'fieldCondition',
        'arguments' => array('academic_year', 'tid', $academic_years, 'IN'),
      );
    }
  }
  
  // Type
  if(!empty($query['article_type'])) {
    $parameters[] = array(
      'type' => 'fieldCondition',
      'arguments' => array('article_type', 'value', $query['article_type']),
    );
  }
  
  // Exclude
  if(!empty($query['nids_not_in'])) {
    $parameters[] = array(
      'type' => 'entityCondition',
      'arguments' => array('entity_id', $query['nids_not_in'], 'NOT IN'),
    );
  }

  return $parameters;
}