<?php

    /**
     * @file
     * Õppeainete loogika
     * 
     * 
     * Loome Sonastikule valjad
     */
    function hitsa_subjects_create_paragraphs(){
      ///////////Tekitame paragraafile bundle///////////////
      $bundle = paragraphs_bundle_load('co');
      if (!$bundle) {
        $bundle = new stdClass();
        $bundle->name = 'Food'; // user friendly label
        $bundle->bundle = 'co'; // machine name
        $bundle->locked = 0;
        $status = paragraphs_bundle_save($bundle);
      }
      ///////////Loome paragraafile valjad///////////////
      ///////////Kursused taksonoomiast//////////////////
      $field = field_info_field('field_class_group');
      $instances = array();
      if (!$field) {
        $field = array(
          'active' => 1,
          'cardinality' => 1,
          'deleted' => 0,
          'entity_types' => array(),
          'field_name' => 'field_class_group',
          'indexes' => array(
            'target_id' => array(
              0 => 'target_id',
            ),
          ),
          'locked' => 0,
          'module' => 'entityreference',
          'settings' => array(
            'handler' => 'base',
            'handler_settings' => array(
              'behaviors' => array(
                'views-select-list' => array(
                  'status' => 0,
                ),
              ),
              'sort' => array(
                'type' => 'none',
              ),
              'target_bundles' => array(
                'class_group' => 'class_group',
              ),
            ),
            'target_type' => 'taxonomy_term',
          ),
          'translatable' => 0,
          'type' => 'entityreference',);
        $field = field_create_field($field); 
      }
      $instances[] = array(
        'bundle' => 'co',
        'default_value' => NULL,
        'deleted' => 0,
        'description' => '',
        'display' => array(
          'default' => array(
            'label' => 'above',
            'module' => 'entityreference',
            'settings' => array(
              'bypass_access' => FALSE,
              'link' => FALSE,
            ),
            'type' => 'entityreference_label',
            'weight' => 2,
          ),
          'paragraphs_editor_preview' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
        ),
        'entity_type' => 'paragraphs_item',
        'field_name' => 'field_class_group',
        'label' => 'Class/Group',
        'required' => 0,
        'settings' => array(
          'user_register_form' => FALSE,
        ),
        'widget' => array(
          'active' => 1,
          'module' => 'options',
          'settings' => array(),
          'type' => 'options_select',
          'weight' => 0,
        ),
        );
        $field_name = 'field_course_count';
        $field = field_info_field($field_name);
        if (!$field) {
          $field = array(
            'active' => 1,
            'cardinality' => 1,
            'deleted' => 0,
            'entity_types' => array(),
            'field_name' => 'field_course_count',
            'indexes' => array(),
            'locked' => 0,
            'module' => 'number',
            'settings' => array(),
            'translatable' => 0,
            'type' => 'number_integer',
            );
            $field = field_create_field($field);
        }
        $instances[] = array(
          'bundle' => 'co',
          'default_value' => NULL,
          'deleted' => 0,
          'description' => 'Kursute arv klassil/õpperühmal',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'number',
              'settings' => array(
                'decimal_separator' => '.',
                'prefix_suffix' => TRUE,
                'scale' => 0,
                'thousand_separator' => '',
              ),
              'type' => 'number_integer',
              'weight' => 1,
            ),
            'paragraphs_editor_preview' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => 0,
            ),
          ),
          'entity_type' => 'paragraphs_item',
          'field_name' => 'field_course_count',
          'label' => 'Course count',
          'required' => 0,
          'settings' => array(
            'max' => '',
            'min' => 0,
            'prefix' => '',
            'suffix' => '',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'number',
            'settings' => array(),
            'type' => 'number',
            'weight' => 1,
          ),
          );
         //  Create an instance of the field and bind it to the bundle.
        foreach ($instances as $instance) {
            field_create_instance($instance);
        }
    }
    /**
     * Loome väljad õppeainetele
     */ 
    function hitsa_subjects_create_fields(){
      $bundle = 'subject';
      
      $field_name = 'field_course_count_subject';
      
      $field = field_info_field($field_name);
      
      if(!$field){
        $field = array(
          'active' => 1,
          'cardinality' => -1,
          'deleted' => 0,
          'entity_types' => array(),
          'field_name' => 'field_course_count_subject',
          'indexes' => array(),
          'locked' => 0,
          'module' => 'paragraphs',
          'settings' => array(),
          'translatable' => 0,
          'type' => 'paragraphs',
          );
        $field = field_create_field($field);  
      }
      $instances = array();
      
      $instances[] = array(
          'bundle' => 'subject',
          'default_value' => NULL,
          'deleted' => 0,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'paragraphs',
              'settings' => array(
                'view_mode' => 'full',
              ),
              'type' => 'paragraphs_view',
              'weight' => 3,
            ),
            'teaser' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => 0,
            ),
          ),
          'entity_type' => 'node',
          'field_name' => 'field_course_count_subject',
          'label' => 'Course count',
          'required' => 0,
          'settings' => array(
            'add_mode' => 'select',
            'allowed_bundles' => array(
              'catering_food_by_day' => -1,
              'co' => 'co',
            ),
            'bundle_weights' => array(
              'catering_food_by_day' => 2,
              'co' => -4,
            ),
            'default_edit_mode' => 'open',
            'title' => 'Paragraph',
            'title_multiple' => 'Paragraphs',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 0,
            'module' => 'paragraphs',
            'settings' => array(),
            'type' => 'paragraphs_embed',
            'weight' => 6,
          ),
        );
        $field_name = 'field_pdf';
        $field = field_info_field($field_name);
        if (!$field) {
          $field = array(
            'active' => 1,
            'cardinality' => -1,
            'deleted' => 0,
            'entity_types' => array(),
            'field_name' => 'field_pdf',
            'indexes' => array(
              'fid' => array(
                0 => 'fid',
              ),
            ),
            'locked' => 0,
            'module' => 'file',
            'settings' => array(
              'display_default' => 0,
              'display_field' => 0,
              'uri_scheme' => 'public',
            ),
            'translatable' => 0,
            'type' => 'file',
            );
          $field = field_create_field($field);
        }
        $instances[] = array(
          'bundle' => 'subject',
          'deleted' => 0,
          'description' => '',
          'display' => array(
            'default' => array(
              'label' => 'above',
              'module' => 'file',
              'settings' => array(),
              'type' => 'file_default',
              'weight' => 1,
            ),
            'teaser' => array(
              'label' => 'above',
              'settings' => array(),
              'type' => 'hidden',
              'weight' => 0,
            ),
          ),
          'entity_type' => 'node',
          'field_name' => 'field_pdf',
          'label' => 'PDF',
          'required' => 0,
          'settings' => array(
            'description_field' => 0,
            'file_directory' => 'aine_dokumendid',
            'file_extensions' => 'txt pdf doc',
            'max_filesize' => '',
            'user_register_form' => FALSE,
          ),
          'widget' => array(
            'active' => 1,
            'module' => 'media',
            'settings' => array(
              'allowed_schemes' => array(
                'public' => 'public',
              ),
              'allowed_types' => array(
                'audio' => 0,
                'document' => 0,
                'image' => 'image',
                'video' => 0,
              ),
              'browser_plugins' => array(
                'media_browser_plus--media_browser_my_files' => 0,
                'media_browser_plus--media_browser_thumbnails' => 'media_browser_plus--media_browser_thumbnails',
                'media_default--media_browser_1' => 0,
                'media_default--media_browser_my_files' => 0,
                'upload' => 'upload',
              ),
            ),
            'type' => 'media_generic',
            'weight' => 4,
          ),
          );
          $field_name = 'body';
          $field = field_info_field($field_name);
          if(!$field){
            $field = array(
            'active' => 1,
            'cardinality' => 1,
            'deleted' => 0,
            'entity_types' => array(
              0 => 'node',
            ),
            'field_name' => 'body',
            'indexes' => array(
              'format' => array(
                0 => 'format',
              ),
            ),
            'locked' => 0,
            'module' => 'text',
            'settings' => array(),
            'translatable' => 0,
            'type' => 'text_with_summary',
          );
          $field = field_create_field($field);
          }
          $instances[] = array(
            'bundle' => 'subject',
            'default_value' => NULL,
            'deleted' => 0,
            'description' => '',
            'display' => array(
              'default' => array(
                'label' => 'hidden',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 0,
              ),
              'teaser' => array(
                'label' => 'hidden',
                'module' => 'text',
                'settings' => array(
                  'trim_length' => 600,
                ),
                'type' => 'text_summary_or_trimmed',
                'weight' => 0,
              ),
            ),
            'entity_type' => 'node',
            'field_name' => 'body',
            'label' => 'Body',
            'required' => FALSE,
            'settings' => array(
              'display_summary' => TRUE,
              'text_processing' => 1,
              'user_register_form' => FALSE,
            ),
            'widget' => array(
              'module' => 'text',
              'settings' => array(
                'rows' => 20,
                'summary_rows' => 5,
              ),
              'type' => 'text_textarea_with_summary',
              'weight' => 1,
            ),
            );
          $field_name = 'field_content_picture';
          $field = field_info_field($field_name);
          if (!$field) {
            $field = array(
              'active' => 1,
              'cardinality' => -1,
              'deleted' => 0,
              'entity_types' => array(),
              'field_name' => 'field_content_picture',
              'indexes' => array(
                'fid' => array(
                  0 => 'fid',
                ),
              ),
              'locked' => 0,
              'module' => 'image',
              'settings' => array(
                'default_image' => 0,
                'uri_scheme' => 'public',
              ),
              'translatable' => 0,
              'type' => 'image',
              );
            $field = file_create_field($field);
          }
          $instances[] = array(
            'bundle' => 'subject',
            'deleted' => 0,
            'description' => '',
            'display' => array(
              'default' => array(
                'label' => 'above',
                'module' => 'image',
                'settings' => array(
                  'image_link' => '',
                  'image_style' => '',
                ),
                'type' => 'image',
                'weight' => 2,
              ),
              'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
              ),
            ),
            'entity_type' => 'node',
            'field_name' => 'field_content_picture',
            'label' => 'Sisu pilt',
            'required' => 0,
            'settings' => array(
              'alt_field' => 0,
              'default_image' => 0,
              'file_directory' => '',
              'file_extensions' => 'png gif jpg jpeg',
              'max_filesize' => '20 MB',
              'max_resolution' => '',
              'min_resolution' => '',
              'title_field' => 0,
              'user_register_form' => FALSE,
            ),
            'widget' => array(
              'active' => 1,
              'module' => 'media',
              'settings' => array(
                'allowed_schemes' => array(
                  'public' => 'public',
                ),
                'allowed_types' => array(
                  'audio' => 0,
                  'document' => 0,
                  'image' => 'image',
                  'video' => 0,
                ),
                'browser_plugins' => array(
                  'media_browser_plus--media_browser_my_files' => 0,
                  'media_browser_plus--media_browser_thumbnails' => 'media_browser_plus--media_browser_thumbnails',
                  'media_default--media_browser_1' => 0,
                  'media_default--media_browser_my_files' => 0,
                  'upload' => 'upload',
                ),
              ),
              'type' => 'media_generic',
              'weight' => 5,
            ),
            );
       //  Create an instance of the field and bind it to the bundle.
      foreach ($instances as $instance) {
          field_create_instance($instance);
      }
    }