<?php
  
  /*
  * Implements hook_install.
  */
  function  hitsa_subjects_install(){
    
        
        $site_default_language = language_default();
        //////////////////Defineerime muutujad//////////////////////////////////////////////
        $cont_name = 'subject';
        $voc_name  = 'class_group';
        //////////////////Loome sisutüübid/////////////////////////////////////////////////
        
        $types = array(
            array(
            'type' => 'subject',
            'name' => st('Subject'),
            'base' => 'node_content',
            'description' => st("One subject"),
            'default_language' => $site_default_language->language,
            'custom' => 1,
            'modified' => 1,
            'locked' => 0,
            ),
         );
    
         foreach ($types as $type) {
              $type = node_type_set_defaults($type);
              node_type_save($type);
            //   node_add_body_field($type);
         }
        //////////////////Kontrollime kas sõnastik eksisteerib//////////////////////////////
        
        $vocab = taxonomy_vocabulary_machine_name_load($voc_name);
        if (empty($vocab)) {
            ////////////////Kui ei eksisteeri loome uue sõnastiku
            $new_taxonomy = (object) array(
              'name' => 'Class/Group',
              'machine_name' => 'class_group',
              'description' => '',
              'hierarchy' => 0,
              'module' => 'taxonomy',
              'weight' => 0,
              'language' => 'und',
              'i18n_mode' => 4,
              'rdf_mapping' => array(
                'rdftype' => array(
                  0 => 'skos:ConceptScheme',
                ),
                'name' => array(
                  'predicates' => array(
                    0 => 'dc:title',
                  ),
                ),
                'description' => array(
                  'predicates' => array(
                    0 => 'rdfs:comment',
                  ),
                ),
              ),
              );  
            taxonomy_vocabulary_save($new_taxonomy);  
        } 
        hitsa_subjects_create_paragraphs($voc_name);
        hitsa_subjects_create_fields();
  }
  
  function hitsa_subjects_uninstall(){
    $instances = field_info_instances('paragraphs_item', 'co');
    foreach ($instances as $instance_name => $field_instance) {
        field_delete_instance($field_instance);
    }
    // find all fields and delete instance
    $instances = field_info_instances('node', 'subject');
    foreach ($instances as $instance_name => $instance) {
            field_delete_instance($instance);
    }
  }