<?php
    /**
     * @file
     * Taksonoomia loogika
     * 
     * 
     * Loome Sonastikule valjad
     */
    function hitsa_content_information_create_fields($voc_name) {
        $field_name = 'information_image';
        //Load field
        $field = field_info_field($field_name);
        //If no field found
        if (!$field) {
            $field = array(
                'active' => 1,
                'cardinality' => 1,
                'deleted' => 0,
                'entity_types' => array(),
                'field_name' => $field_name,
                'indexes' => array(
                  'fid' => array(
                    0 => 'fid',
                  ),
                ),
                'label' => 'Image',
                'locked' => 0,
                'module' => 'image',
                'settings' => array(
                  'default_image' => 0,
                  'uri_scheme' => 'public',
                ),
                'translatable' => 0,
                'type' => 'image',
                );
            $field = field_create_field($field);
        } 
        if ($field) {
            $instances[] = array(
                'bundle' => $voc_name,
                'field_name' => $field['field_name'],
                'deleted' => 0,
                'description' => '',
                'display' => array(
                  'default' => array(
                    'label' => 'above',
                    'module' => 'image',
                    'settings' => array(
                      'image_link' => '',
                      'image_style' => '',
                    ),
                    'type' => 'image',
                    'weight' => 0,
                  ),
                ),
                'entity_type' => 'taxonomy_term',
                'label' => st('Content information image'),
                'required' => 0,
                'settings' => array(
                  'alt_field' => 0,
                  'default_image' => 0,
                  'file_directory' => 'sisu_informatsioon',
                  'file_extensions' => 'png gif jpg jpeg',
                  'max_filesize' => '',
                  'max_resolution' => '',
                  'min_resolution' => '',
                  'title_field' => 0,
                  'user_register_form' => FALSE,
                ),
                'widget' => array(
                  'active' => 1,
                  'module' => 'media',
                  'settings' => array(
                    'allowed_schemes' => array(
                      'public' => 'public',
                    ),
                    'allowed_types' => array(
                      'audio' => 0,
                      'document' => 0,
                      'image' => 'image',
                      'video' => 0,
                    ),
                    'browser_plugins' => array(
                      'media_default--media_browser_1' => 0,
                      'media_default--media_browser_my_files' => 0,
                      'upload' => 'upload',
                    ),
                  ),
                  'type' => 'media_generic',
                  'weight' => 42,
                ),
                );
        }
            
        foreach ($instances as $instance) {
            field_create_instance($instance);
        }
    }