<?php
module_load_include('inc', 'hitsa_gallery', 'includes/hitsa_gallery.theme');

function hitsa_gallery_node_info() {
  return array(
    'gallery' => array(
      'name' => t('Gallery'),
      'base' => 'gallery',
      'description' => t('Gallery container.'),
      'has_title' => TRUE,
      'title_label' => t('Title'),
    ),
  );
}

function hitsa_gallery_menu() {
  $items['gallery'] = array(
    'title' => 'Gallery',
    'page callback' => 'hitsa_gallery_page_view',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'hitsa-header-menu',
    'weight' => 1,
  );
  
  $items['api/gallery'] = array(
    'title' => 'Gallery API',
    'page callback' => 'hitsa_gallery_filter',
    'access arguments' => array('access content'),
  );
  
  $items['api/gallery-autocomplete'] = array(
    'title' => 'Gallery API',
    'page callback' => 'hitsa_gallery_autocomplete',
    'access arguments' => array('access content'),
  );
  
  return $items;
}

/**
 * Implement hook_form()
 */
function gallery_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

function hitsa_gallery_filter() {
  global $language;
  
  $output = hitsa_gallery_page_view(TRUE);
  
  print $output;
  exit;
}

function hitsa_gallery_autocomplete() {
  hitsa_content_page_autocomplete('gallery');
}

function hitsa_gallery_block_info() {
  $blocks['hitsa_gallery_fp'] = array(
    'info' => t('HITSA Gallery'),
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '<front>',
    'region' => 'content',
    'status' => "1",
  );
  
  return $blocks;
}

function hitsa_gallery_block_view($delta = '') {
  $output = array();
  switch($delta) {
    case 'hitsa_gallery_fp' :
      $content = hitsa_gallery_fp_block();
      $output = array('subject' => NULL, 'content' => $content);
  }
  
  return $output;
}

function hitsa_gallery_fp_block() {
  $output = '';
  
  $query = array();
  $query['range'] = array(0, 3);
  $query['entity_type'] = 'node';
  $query['bundle'] = 'gallery';
  $query['status'] = NODE_PUBLISHED;
  $query['order_by'] = array('parameter' => 'created', 'direction' => 'DESC');
  
  if($result = hitsa_content_page_query_content($query, TRUE)) {
    $nids_array = !empty($result['content']) ? $result['content'] : NULL;
    
    if(!empty($nids_array)) {
      $nodes = node_load_multiple(array_keys($nids_array['node']));
      $nodes_rendered = array();
      
      //dpm($nodes);
      
      foreach($nodes as $node) {
        $nodes_rendered[] = node_view($node);
      }
      
      $content = theme('hitsa_gallery_fp', array('nodes' => $nodes_rendered));
      return $content;
    }
  }
  return $output;
}