<?php

/**
 * Implements hook_install().
 */
function hitsa_curriculum_install()
{
    module_load_include('module','hitsa_core','hitsa_core');
    $school_type = '';
    if (empty(variable_get('hitsa_school_type'))) {
        variable_set('hitsa_school_type', 1);
        $school_type = 1;
    }
    else{
      $school_type =  variable_get('hitsa_school_type');
    }
    hitsa_curriculum_create_node();

    $types = node_type_get_types();
    hitsa_curriculum_add_custom_vocabularies();
    hitsa_curriculum_add_custom_taxonomy_fields();
    hitsa_curriculum_add_custom_paragraphs_bundle();

    hitsa_curriculum_add_custom_paragraphs_fields();
    hitsa_curriculum_add_custom_node_fields($school_type);
    hitsa_curriculum_make_fields_conditional();
    // hitsa_curriculum_add_custom_field_groups();

    hitsa_curriculum_create_translations();
}
/**
 * Implements hook_uninstall().
 */
function hitsa_curriculum_uninstall()
{
    $node_type = 'curriculum';
    $paragraphs_bundles = array(
        'contacts', 'description', 'table', 'jobs'
    );


    $sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
    $result = db_query($sql, array(':type' => $node_type));
    $node_ids = array();
    foreach ($result as $row) {
        $node_ids[] = $row->nid;
    }
    $school_type = hitsa_core_get_school_type();
    if (empty(variable_get('hitsa_school_type'))) {
        variable_set('hitsa_school_type', 1);
        $school_type = 1;
    }

    // Delete fields and vocabularies
    hitsa_curriculum_delete_custom_node_fields($school_type);
    hitsa_curriculum_delete_custom_paragraphs_fields();
    field_purge_batch(500);
    hitsa_curriculum_delete_custom_vocabularies();
    // hitsa_curriculum_delete_vocabulary_fields();
    node_delete_multiple($node_ids); // Delete all catering nodes
    node_type_delete($node_type); // Delete contact content type
    foreach ($paragraphs_bundles as $key => $paragraphs_bundle) {
        paragraphs_bundle_delete($paragraphs_bundle); // Delete paragraphs bundle
    }
}
function hitsa_curriculum_add_custom_vocabularies()
{

    foreach (_hitsa_curriculum_vocabularies() as $v) {
        taxonomy_vocabulary_save($v['vocabulary']);

        $vocab = taxonomy_vocabulary_machine_name_load($v['vocabulary']->machine_name);
        if (!empty($v['terms']) && $vocab) {
            // Add generic terms
            foreach ($v['terms'] as $term) {
                $term->vid = $vocab->vid;
                taxonomy_term_save($term);
            }
        }
    }
}
function _hitsa_curriculum_vocabularies()
{

    $vocabularies = array();

    $vocabularies['fields'] = array(
        'vocabulary' => (object)array(
            'name' => t('Fields'),
            'description' => t('Field for speciality'),
            'machine_name' => 'fields',
            'hierarchy' => 0,
            'module' => 'taxonomy',
            'weight' => 0,
            'language' => 'und',
            'i18n_mode' => 1,
            'rdf_mapping' => array(
                'rdftype' => array(
                    0 => 'skos:ConceptScheme',
                ),
                'name' => array(
                    'predicates' => array(
                        0 => 'dc:title',
                    ),
                ),
                'description' => array(
                    'predicates' => array(
                        0 => 'rdfs:comment',
                    ),
                ),
            ),
        ),
    );
    return $vocabularies;
}
function hitsa_curriculum_delete_custom_vocabularies()
{
    foreach (_hitsa_curriculum_vocabularies() as $v) {
        if (!empty($v['vocabulary'])) {
            $vocab = taxonomy_vocabulary_machine_name_load($v['vocabulary']->machine_name);
            taxonomy_vocabulary_delete($vocab->vid);
        }
    }
}
function hitsa_curriculum_add_custom_paragraphs_bundle()
{
    $bundle = new stdClass();
    $bundle->name = t('Contacts'); // user friendly label
    $bundle->bundle = 'contacts'; // machine name
    $bundle->locked = 1;
    $status = paragraphs_bundle_save($bundle);
    $bundle = new stdClass();
    $bundle->name = t('Description'); // user friendly label
    $bundle->bundle = 'description'; // machine name
    $bundle->locked = 1;
    $status = paragraphs_bundle_save($bundle);
    $bundle = new stdClass();
    $bundle->name = t('Table'); // user friendly label
    $bundle->bundle = 'table'; // machine name
    $bundle->locked = 1;
    $status = paragraphs_bundle_save($bundle);
    $status = paragraphs_bundle_save($bundle);
    $bundle = new stdClass();
    $bundle->name = t('Jobs'); // user friendly label
    $bundle->bundle = 'jobs'; // machine name
    $bundle->locked = 1;
    $status = paragraphs_bundle_save($bundle);
}
function hitsa_curriculum_add_custom_paragraphs_fields()
{

    foreach (_hitsa_curriculum_installed_paragraphs_fields() as $field) {
        $field_test = field_info_field($field['field_name']);
        if (empty($field_test)) {
            field_create_field($field);
        }
    }

    foreach (_hitsa_curriculum_installed_paragraphs_instances() as $field_instance) {
        field_create_instance($field_instance);
    }
}
function _hitsa_curriculum_installed_paragraphs_fields()
{

    $field_bases = array();

    // Exported field_base: 'field_address'.
    $field_bases['field_address'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_address',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_contact_email'.
    $field_bases['field_contact_email'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_contact_email',
        'indexes' => array(),
        'locked' => 0,
        'module' => 'email',
        'settings' => array(
            'entity_translation_sync' => false,
        ),
        'translatable' => 0,
        'type' => 'email',
    );

    // Exported field_base: 'field_contact_title'.
    $field_bases['field_contact_title'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_contact_title',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_phone_number'.
    $field_bases['field_phone_number'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_phone_number',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'add_row_localization_source' => 'Add another item',
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_website'.
    $field_bases['field_website'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_website',
        'indexes' => array(),
        'locked' => 0,
        'module' => 'link',
        'settings' => array(
            'attributes' => array(
                'class' => '',
                'rel' => '',
                'target' => 'default',
            ),
            'display' => array(
                'url_cutoff' => 80,
            ),
            'enable_tokens' => 1,
            'entity_translation_sync' => false,
            'title' => 'optional',
            'title_maxlength' => 128,
            'title_value' => '',
            'url' => 0,
        ),
        'translatable' => 0,
        'type' => 'link_field',
    );

    return $field_bases;

}
function _hitsa_curriculum_installed_paragraphs_instances()
{

    $field_instances = array();

    // Exported field_instance: 'paragraphs_item-contacts-field_address'.
    $field_instances['paragraphs_item-contacts-field_address'] = array(
        'bundle' => 'contacts',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 3,
            ),
            'paragraphs_editor_preview' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'paragraphs_item',
        'field_name' => 'field_address',
        'label' => 'Address',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 5,
        ),
    );

    // Exported field_instance: 'paragraphs_item-contacts-field_contact_email'.
    $field_instances['paragraphs_item-contacts-field_contact_email'] = array(
        'bundle' => 'contacts',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'email',
                'settings' => array(),
                'type' => 'email_default',
                'weight' => 4,
            ),
            'paragraphs_editor_preview' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'paragraphs_item',
        'field_name' => 'field_contact_email',
        'label' => 'Email',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'email',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'email_textfield',
            'weight' => 2,
        ),
    );

    // Exported field_instance: 'paragraphs_item-contacts-field_contact_title'.
    $field_instances['paragraphs_item-contacts-field_contact_title'] = array(
        'bundle' => 'contacts',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 0,
            ),
            'paragraphs_editor_preview' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'paragraphs_item',
        'field_name' => 'field_contact_title',
        'label' => 'Contact title',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 1,
        ),
    );

    // Exported field_instance: 'paragraphs_item-contacts-field_phone_number'.
    $field_instances['paragraphs_item-contacts-field_phone_number'] = array(
        'bundle' => 'contacts',
        'default_value' => null,
        'deleted' => 0,
        'description' => '+372 000000',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 2,
            ),
            'paragraphs_editor_preview' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'paragraphs_item',
        'field_name' => 'field_phone_number',
        'label' => 'Phone number',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 4,
        ),
    );

    // Exported field_instance: 'paragraphs_item-contacts-field_website'.
    $field_instances['paragraphs_item-contacts-field_website'] = array(
        'bundle' => 'contacts',
        'default_value' => null,
        'deleted' => 0,
        'description' => 'Lingi kiri, kui seda ei sisestata tuleb selle asemele lingi URL',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'link',
                'settings' => array(),
                'type' => 'link_default',
                'weight' => 5,
            ),
            'paragraphs_editor_preview' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'paragraphs_item',
        'field_name' => 'field_website',
        'label' => 'Website',
        'required' => 0,
        'settings' => array(
            'absolute_url' => 1,
            'attributes' => array(
                'class' => '',
                'configurable_class' => 0,
                'configurable_title' => 0,
                'rel' => '',
                'target' => 'default',
                'title' => '',
            ),
            'display' => array(
                'url_cutoff' => 80,
            ),
            'enable_tokens' => 1,
            'entity_translation_sync' => false,
            'rel_remove' => 'default',
            'title' => 'optional',
            'title_label_use_field_label' => 0,
            'title_maxlength' => 128,
            'title_value' => '',
            'url' => 0,
            'user_register_form' => false,
            'validate_url' => 1,
        ),
        'widget' => array(
            'active' => 0,
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_field',
            'weight' => 1,
        ),
    );

    // Translatables
    // Included for use with string extractors like potx.
    t('+372 000000');
    t('Address');
    t('Contact title');
    t('Email');
    t('Lingi kiri, kui seda ei sisestata tuleb selle asemele lingi URL');
    t('Phone number');
    t('Website');

    return $field_instances;

}
function hitsa_curriculum_delete_custom_paragraphs_fields()
{

    foreach (_hitsa_curriculum_installed_paragraphs_fields() as $field_key => $field) {

        $field_info = field_info_field($field_key);
//        field_delete_field($field_key);
    }
    $instances = field_info_instances('paragraphs_item', 'contacts');
    foreach ($instances as $instance_name => $field_instance) {
        field_delete_instance($field_instance);
    }
    $instances = field_info_instances('paragraphs_item', 'description');
    foreach ($instances as $instance_name => $field_instance) {
        field_delete_instance($field_instance);
    }
    $instances = field_info_instances('paragraphs_item', 'table');
    foreach ($instances as $instance_name => $field_instance) {
        field_delete_instance($field_instance);
    }
}
function hitsa_curriculum_add_custom_node_fields($school_type)
{
    foreach (_hitsa_curriculum_installed_node_fields($school_type) as $field) {

        $field_test = field_info_field($field['field_name']);
        if (empty($field_test)) {
            field_create_field($field);
        }
    }

    foreach (_hitsa_curriculum_installed_node_instances() as $field_instance) {
        field_create_instance($field_instance);
    }
}
function _hitsa_curriculum_installed_node_fields($school_type = null)
{


    if ($school_type == 1) {
        $subtypes = array(
            'specialities' => 'Speciality',
            'elective-courses' => 'Elective courses',
            'accommodation' => 'Accommodation',
            'hobby-activity' => 'Hobby activity',
            'sport-facilities' => 'Sport facilities',
            'training-scholarships' => 'Training Scholarships',
            'e-course' => 'E-Course',
            'catering' => 'Catering',
            'ordered-trainings' => 'Ordered trainings',
            'certification-exams' => 'Certification exams',
            'cooperation-and-partners' => 'Cooperation and projects',
        );
    } elseif ($school_type == 2) {
        $subtypes = array(
            'subject-field' => 'Subject field',
            'boarding-school' => 'Boarding school',
            'hobby-groups' => 'Hobby Groups',
            'sport' => 'Sport',
            'cooperation' => 'Cooperation',
        );
    }
    $subtypes['vacancies'] = 'Vacancies';
    $subtypes['publications'] = 'Publications';
    $subtypes['preparatory-courses'] = 'Preparatory courses';
    $subtypes['publications'] = 'Publications';
    $subtypes['elective-subjects'] = 'Elective subjects';
    // Exported field_base: 'body'.
    $field_bases = array();
    $field_bases['body'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(
            0 => 'node',
        ),
        'field_name' => 'body',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
        ),
        'translatable' => 0,
        'type' => 'text_with_summary',
    );

    // Exported field_base: 'field_assessment'.
    $field_bases['field_assessment'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_assessment',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_attachments'.
    $field_bases['field_attachments'] = array(
        'active' => 1,
        'cardinality' => -1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_attachments',
        'indexes' => array(
            'fid' => array(
                0 => 'fid',
            ),
        ),
        'locked' => 0,
        'module' => 'file',
        'settings' => array(
            'display_default' => 0,
            'display_field' => 0,
            'entity_translation_sync' => array(
                0 => 'fid',
            ),
            'uri_scheme' => 'public',
        ),
        'translatable' => 0,
        'type' => 'file',
    );

    // Exported field_base: 'field_contacts'.
    $field_bases['field_contacts'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_contacts',
        'indexes' => array(),
        'locked' => 0,
        'module' => 'paragraphs',
        'settings' => array(
            'entity_translation_sync' => false,
        ),
        'translatable' => 0,
        'type' => 'paragraphs',
    );

    // Exported field_base: 'field_curriculum_length'.
    $field_bases['field_curriculum_length'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_curriculum_length',
        'indexes' => array(),
        'locked' => 0,
        'module' => 'date',
        'settings' => array(
            'add_row_localization_source' => 'Add another item',
            'cache_count' => 4,
            'cache_enabled' => 0,
            'entity_translation_sync' => false,
            'granularity' => array(
                'day' => 'day',
                'hour' => 0,
                'minute' => 0,
                'month' => 'month',
                'second' => 0,
                'year' => 'year',
            ),
            'timezone_db' => '',
            'todate' => 'required',
            'tz_handling' => 'none',
        ),
        'translatable' => 0,
        'type' => 'datestamp',
    );

    // Exported field_base: 'field_curriculum_start'.
    $field_bases['field_curriculum_start'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_curriculum_start',
        'indexes' => array(),
        'locked' => 0,
        'module' => 'date',
        'settings' => array(
            'add_row_localization_source' => 'Add another item',
            'cache_count' => 4,
            'cache_enabled' => 0,
            'entity_translation_sync' => false,
            'granularity' => array(
                'day' => 'day',
                'hour' => 'hour',
                'minute' => 'minute',
                'month' => 'month',
                'second' => 0,
                'year' => 'year',
            ),
            'timezone_db' => 'UTC',
            'todate' => '',
            'tz_handling' => 'site',
        ),
        'translatable' => 0,
        'type' => 'datestamp',
    );

    // Exported field_base: 'field_days_place'.
    $field_bases['field_days_place'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_days_place',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_field'.
    $field_bases['field_field'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_field',
        'indexes' => array(
            'target_id' => array(
                0 => 'target_id',
            ),
        ),
        'locked' => 0,
        'module' => 'entityreference',
        'settings' => array(
            'entity_translation_sync' => false,
            'handler' => 'base',
            'handler_settings' => array(
                'behaviors' => array(
                    'views-select-list' => array(
                        'status' => 0,
                    ),
                ),
                'sort' => array(
                    'type' => 'none',
                ),
                'target_bundles' => array(
                    'fields' => 'fields',
                ),
            ),
            'target_type' => 'taxonomy_term',
        ),
        'translatable' => 0,
        'type' => 'entityreference',
    );

    // Exported field_base: 'field_instructor'.
    $field_bases['field_instructor'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_instructor',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_jobs'.
    $field_bases['field_jobs'] = array(
        'active' => 1,
        'cardinality' => -1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_jobs',
        'indexes' => array(),
        'locked' => 0,
        'module' => 'paragraphs',
        'settings' => array(
            'entity_translation_sync' => false,
        ),
        'translatable' => 0,
        'type' => 'paragraphs',
    );

    // Exported field_base: 'field_jobs_pretext'.
    $field_bases['field_jobs_pretext'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_jobs_pretext',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
        ),
        'translatable' => 0,
        'type' => 'text_with_summary',
    );

    // Exported field_base: 'field_pictures'.
    $field_bases['field_pictures'] = array(
        'active' => 1,
        'cardinality' => 2,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_pictures',
        'indexes' => array(
            'fid' => array(
                0 => 'fid',
            ),
        ),
        'locked' => 0,
        'module' => 'image',
        'settings' => array(
            'add_row_localization_source' => 'Add another item',
            'default_image' => 0,
            'entity_translation_sync' => array(
                0 => 'fid',
            ),
            'uri_scheme' => 'public',
        ),
        'translatable' => 0,
        'type' => 'image',
    );

    // Exported field_base: 'field_premise'.
    $field_bases['field_premise'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_premise',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_rating'.
    $field_bases['field_rating'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_rating',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_room'.
    $field_bases['field_room'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_room',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_school_selections'.

    $field_bases['field_school_selections'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_school_selections',
        'indexes' => array(
            'value' => array(
                0 => 'value',
            ),
        ),
        'locked' => 1,
        'module' => 'list',
        'settings' => array(
            'allowed_values' => $subtypes,
            'allowed_values_function' => '',
            'entity_translation_sync' => false,
        ),
        'translatable' => 0,
        'type' => 'list_text',
    );

    // Exported field_base: 'field_short_description'.
    $field_bases['field_short_description'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_short_description',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'add_row_localization_source' => 'Add another item',
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_specialitiy_table'.
    $field_bases['field_specialitiy_table'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_specialitiy_table',
        'indexes' => array(),
        'locked' => 0,
        'module' => 'tablefield',
        'settings' => array(
            'add_row_localization_source' => 'Add another item',
            'entity_translation_sync' => false,
        ),
        'translatable' => 0,
        'type' => 'tablefield',
    );

    // Exported field_base: 'field_subjects_table'.
    $field_bases['field_subjects_table'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_subjects_table',
        'indexes' => array(),
        'locked' => 0,
        'module' => 'tablefield',
        'settings' => array(
            'add_row_localization_source' => 'Add another item',
            'entity_translation_sync' => false,
        ),
        'translatable' => 0,
        'type' => 'tablefield',
    );

    // Exported field_base: 'field_table_description'.
    $field_bases['field_table_description'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_table_description',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'add_row_localization_source' => 'Add another item',
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_table_descriptions'.
    $field_bases['field_table_descriptions'] = array(
        'active' => 1,
        'cardinality' => -1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_table_descriptions',
        'indexes' => array(),
        'locked' => 0,
        'module' => 'paragraphs',
        'settings' => array(
            'entity_translation_sync' => false,
        ),
        'translatable' => 0,
        'type' => 'paragraphs',
    );

    // Exported field_base: 'field_target_group'.
    $field_bases['field_target_group'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_target_group',
        'indexes' => array(
            'format' => array(
                0 => 'format',
            ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
            'entity_translation_sync' => false,
            'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
    );

    // Exported field_base: 'field_textbooks'.
    $field_bases['field_textbooks'] = array(
        'active' => 1,
        'cardinality' => -1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_textbooks',
        'indexes' => array(),
        'locked' => 0,
        'module' => 'link',
        'settings' => array(
            'attributes' => array(
                'class' => '',
                'rel' => '',
                'target' => 'default',
            ),
            'display' => array(
                'url_cutoff' => 80,
            ),
            'enable_tokens' => 1,
            'entity_translation_sync' => false,
            'title' => 'optional',
            'title_maxlength' => 128,
            'title_value' => '',
            'url' => 0,
        ),
        'translatable' => 0,
        'type' => 'link_field',
    );
    return $field_bases;
}
function _hitsa_curriculum_installed_node_instances()
{
    $field_instances = array();

    // Exported field_instance: 'node-curriculum-body'.
    $field_instances['node-curriculum-body'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'hidden',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 0,
            ),
            'teaser' => array(
                'label' => 'hidden',
                'module' => 'text',
                'settings' => array(
                    'trim_length' => 600,
                ),
                'type' => 'text_summary_or_trimmed',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'body',
        'label' => 'Description',
        'required' => 1,
        'settings' => array(
            'display_summary' => 0,
            'entity_translation_sync' => false,
            'text_processing' => 1,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'rows' => 20,
                'summary_rows' => 5,
            ),
            'type' => 'text_textarea_with_summary',
            'weight' => 12,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_assessment'.
    $field_instances['node-curriculum-field_assessment'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 19,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_assessment',
        'label' => 'Assessment',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 21,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_attachments'.
    $field_instances['node-curriculum-field_attachments'] = array(
        'bundle' => 'curriculum',
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'file',
                'settings' => array(),
                'type' => 'file_default',
                'weight' => 5,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_attachments',
        'label' => 'Attachments',
        'required' => 0,
        'settings' => array(
            'description_field' => 0,
            'entity_translation_sync' => false,
            'file_directory' => '',
            'file_extensions' => 'txt pdf doc docx odt rtf wpd tex wps',
            'max_filesize' => '10 MB',
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'media',
            'settings' => array(
                'allowed_schemes' => array(
                    'public' => 'public',
                ),
                'allowed_types' => array(
                    'audio' => 0,
                    'document' => 'document',
                    'image' => 'image',
                    'video' => 0,
                ),
                'browser_plugins' => array(
                    'media_default--media_browser_1' => 'media_default--media_browser_1',
                    'media_default--media_browser_my_files' => 'media_default--media_browser_my_files',
                    'upload' => 'upload',
                ),
            ),
            'type' => 'media_generic',
            'weight' => 24,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_contacts'.
    $field_instances['node-curriculum-field_contacts'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'paragraphs',
                'settings' => array(
                    'view_mode' => 'full',
                ),
                'type' => 'paragraphs_view',
                'weight' => 6,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_contacts',
        'label' => 'Kontaktid',
        'required' => 0,
        'settings' => array(
            'add_mode' => 'button',
            'allowed_bundles' => array(
                'catering_food_by_day' => -1,
                'contacts' => 'contacts',
                'contacts_department' => -1,
                'description' => -1,
                'jobs' => -1,
                'reception_time' => -1,
                'subpage' => -1,
                'table' => -1,
            ),
            'bundle_weights' => array(
                'catering_food_by_day' => 2,
                'contacts' => 3,
                'contacts_department' => 4,
                'description' => 6,
                'jobs' => 14,
                'reception_time' => 15,
                'subpage' => 16,
                'table' => 8,
            ),
            'default_edit_mode' => 'preview',
            'entity_translation_sync' => false,
            'title' => 'kontakt',
            'title_multiple' => 'kontakti',
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 0,
            'module' => 'paragraphs',
            'settings' => array(),
            'type' => 'paragraphs_embed',
            'weight' => 25,
        ),
    );

     // Exported field_instance: 'node-curriculum-field_curriculum_length'.
    $field_instances['node-curriculum-field_curriculum_length'] = array(
        'bundle' => 'curriculum',
        'deleted' => 0,
        'description' => 'Kuupäeva vahemik, millal konkreetne sündmus toimub. Kui tegu ühepevase sündmusega, siis tuleb alguse ja lõpu kuupäevaks valida sama kuupäev.',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'date',
                'settings' => array(
                    'format_type' => 'long',
                    'fromto' => 'both',
                    'multiple_from' => '',
                    'multiple_number' => '',
                    'multiple_to' => '',
                    'show_remaining_days' => false,
                ),
                'type' => 'date_default',
                'weight' => 11,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_curriculum_length',
        'label' => 'Length',
        'required' => 0,
        'settings' => array(
            'default_value' => 'now',
            'default_value2' => 'same',
            'default_value_code' => '',
            'default_value_code2' => '',
            'entity_translation_sync' => false,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'date',
            'settings' => array(
                'increment' => 15,
                'input_format' => 'd/m/Y - H:i:s',
                'input_format_custom' => '',
                'label_position' => 'above',
                'no_fieldset' => 0,
                'text_parts' => array(),
                'year_range' => '-3:+3',
            ),
            'type' => 'date_popup',
            'weight' => 4,
        ),
    );

  // Exported field_instance: 'node-curriculum-field_curriculum_start'.
    $field_instances['node-curriculum-field_curriculum_start'] = array(
        'bundle' => 'curriculum',
        'deleted' => 0,
        'description' => 'Sündmuse algusaeg kellaajaliselt. Täita juhul, kui sündmusel on konkreetne alguse kellaaeg. Kui konkreetne alguse kellaaeg puudub, siis täita ei ole vaja.',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'date',
                'settings' => array(
                    'format_type' => 'long',
                    'fromto' => 'both',
                    'multiple_from' => '',
                    'multiple_number' => '',
                    'multiple_to' => '',
                    'show_remaining_days' => false,
                ),
                'type' => 'date_default',
                'weight' => 12,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_curriculum_start',
        'label' => 'Start ',
        'required' => 0,
        'settings' => array(
            'default_value' => 'now',
            'default_value2' => 'same',
            'default_value_code' => '',
            'default_value_code2' => '',
            'entity_translation_sync' => false,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'date',
            'settings' => array(
                'increment' => 15,
                'input_format' => 'd/m/Y - H:i:s',
                'input_format_custom' => '',
                'label_position' => 'above',
                'no_fieldset' => 0,
                'text_parts' => array(),
                'year_range' => '-3:+3',
            ),
            'type' => 'date_popup',
            'weight' => 5,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_days_place'.
    $field_instances['node-curriculum-field_days_place'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 13,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_days_place',
        'label' => 'Days it takes place',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 7,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_field'.
    $field_instances['node-curriculum-field_field'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'entityreference',
                'settings' => array(
                    'bypass_access' => false,
                    'link' => false,
                ),
                'type' => 'entityreference_label',
                'weight' => 1,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_field',
        'label' => 'Field',
        'required' => 1,
        'settings' => array(
            'behaviors' => array(
                'taxonomy-index' => array(
                    'status' => true,
                ),
            ),
            'entity_translation_sync' => false,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'options',
            'settings' => array(),
            'type' => 'options_select',
            'weight' => 3,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_instructor'.
    $field_instances['node-curriculum-field_instructor'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 14,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_instructor',
        'label' => 'Instructor',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 8,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_jobs'.
    $field_instances['node-curriculum-field_jobs'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'paragraphs',
                'settings' => array(
                    'view_mode' => 'full',
                ),
                'type' => 'paragraphs_view',
                'weight' => 7,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_jobs',
        'label' => 'Töökohad',
        'required' => 0,
        'settings' => array(
            'add_mode' => 'select',
            'allowed_bundles' => array(
                'catering_food_by_day' => -1,
                'contacts' => -1,
                'contacts_department' => -1,
                'description' => -1,
                'jobs' => 'jobs',
                'reception_time' => -1,
                'subpage' => -1,
                'table' => -1,
            ),
            'bundle_weights' => array(
                'catering_food_by_day' => 2,
                'contacts' => 3,
                'contacts_department' => 4,
                'description' => 5,
                'jobs' => 6,
                'reception_time' => 15,
                'subpage' => 16,
                'table' => 8,
            ),
            'default_edit_mode' => 'open',
            'entity_translation_sync' => false,
            'title' => 'töökoht',
            'title_multiple' => 'töökohad',
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 0,
            'module' => 'paragraphs',
            'settings' => array(),
            'type' => 'paragraphs_embed',
            'weight' => 19,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_jobs_pretext'.
    $field_instances['node-curriculum-field_jobs_pretext'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 9,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_jobs_pretext',
        'label' => 'Jobs pretext',
        'required' => 0,
        'settings' => array(
            'display_summary' => 0,
            'entity_translation_sync' => false,
            'text_processing' => 1,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'rows' => 20,
                'summary_rows' => 5,
            ),
            'type' => 'text_textarea_with_summary',
            'weight' => 18,
        ),
    );

   // Exported field_instance: 'node-curriculum-field_pictures'.
  $field_instances['node-curriculum-field_pictures'] = array(
    'bundle' => 'curriculum',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_pictures',
    'label' => 'Pictures',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'entity_translation_sync' => FALSE,
      'file_directory' => 'curriculum_pictures',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'media',
      'settings' => array(
        'allowed_schemes' => array(
          'public' => 'public',
          'youtube' => 0,
        ),
        'allowed_types' => array(
          'audio' => 0,
          'document' => 0,
          'image' => 'image',
          'video' => 0,
        ),
        'browser_plugins' => array(
          'media_default--media_browser_1' => 'media_default--media_browser_1',
          'media_default--media_browser_my_files' => 'media_default--media_browser_my_files',
          'media_internet' => 0,
          'upload' => 'upload',
        ),
        'manualcrop_crop_info' => 1,
        'manualcrop_default_crop_area' => 1,
        'manualcrop_enable' => 0,
        'manualcrop_inline_crop' => 0,
        'manualcrop_instant_crop' => FALSE,
        'manualcrop_instant_preview' => 1,
        'manualcrop_keyboard' => 1,
        'manualcrop_maximize_default_crop_area' => 0,
        'manualcrop_require_cropping' => array(),
        'manualcrop_styles_list' => array(),
        'manualcrop_styles_mode' => 'include',
        'manualcrop_thumblist' => 0,
      ),
      'type' => 'media_generic',
      'weight' => 23,
    ),
  );

    // Exported field_instance: 'node-curriculum-field_premise'.
    $field_instances['node-curriculum-field_premise'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 17,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_premise',
        'label' => 'Premise',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 11,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_rating'.
    $field_instances['node-curriculum-field_rating'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 18,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_rating',
        'label' => 'Rating',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 20,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_room'.
    $field_instances['node-curriculum-field_room'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 15,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_room',
        'label' => 'Room',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 9,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_school_selections'.
    $field_instances['node-curriculum-field_school_selections'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'list',
                'settings' => array(),
                'type' => 'list_default',
                'weight' => 10,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_school_selections',
        'label' => 'Tabbed content page type',
        'required' => 1,
        'settings' => array(
            'entity_translation_sync' => false,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'options',
            'settings' => array(),
            'type' => 'options_select',
            'weight' => 1,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_short_description'.
    $field_instances['node-curriculum-field_short_description'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 28,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_short_description',
        'label' => 'Table title',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 13,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_specialitiy_table'.
    $field_instances['node-curriculum-field_specialitiy_table'] = array(
        'bundle' => 'curriculum',
        'default_value' => array(
            0 => array(
                'tablefield' => array(
                    'caption' => '',
                    'import' => array(
                        'file' => '',
                        'import' => 'Lae CSV üles',
                    ),
                    'paste' => array(
                        'data' => '',
                        'paste_delimiter' => '',
                        'paste_import' => 'Impordi & Uuenda',
                    ),
                    'rebuild' => array(
                        'count_cols' => 4,
                        'count_rows' => 2,
                        'rebuild' => 'Uuenda tabel',
                    ),
                    'tabledata' => array(
                        'row_0' => array(
                            'col_0' => 'Õppeliik',
                            'col_1' => 'Õppevorm',
                            'col_2' => 'Eeldus alustamiseks',
                            'col_3' => 'Õppeaeg',
                            'weight' => 1,
                        ),
                        'row_1' => array(
                            'col_0' => '',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 2,
                        ),
                    ),
                ),
            ),
        ),
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'tablefield',
                'settings' => array(
                    'export_csv' => false,
                    'header_orientation' => 'Horizontal',
                    'hide_cols_skip_head' => false,
                    'hide_empty_cols' => false,
                    'hide_empty_rows' => false,
                    'hide_header' => false,
                    'sortable' => false,
                    'sticky_header' => true,
                    'striping' => true,
                    'trim_trailing_cols' => false,
                    'trim_trailing_rows' => false,
                ),
                'type' => 'tablefield_default',
                'weight' => 23,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_specialitiy_table',
        'label' => 'Erialade tabel',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'tablefield',
            'settings' => array(
                'cell_processing' => 0,
                'data_sources' => array(
                    'paste' => 'paste',
                    'upload' => 'upload',
                ),
                'input_type' => 'textfield',
                'lock_values' => 1,
                'max_length' => 2048,
                'restrict_rebuild' => 0,
            ),
            'type' => 'tablefield',
            'weight' => 16,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_subjects_table'.
    $field_instances['node-curriculum-field_subjects_table'] = array(
        'bundle' => 'curriculum',
        'default_value' => array(
            0 => array(
                'tablefield' => array(
                    'caption' => '',
                    'import' => array(
                        'file' => '',
                        'import' => 'Lae CSV üles',
                    ),
                    'paste' => array(
                        'data' => '',
                        'paste_delimiter' => '',
                        'paste_import' => 'Impordi & Uuenda',
                    ),
                    'rebuild' => array(
                        'count_cols' => 4,
                        'count_rows' => 20,
                        'rebuild' => 'Uuenda tabel',
                    ),
                    'tabledata' => array(
                        'row_0' => array(
                            'col_0' => 'Õppeained (RÕK + LK)',
                            'col_1' => '10.klassi kursused',
                            'col_2' => '11.klassi kursused',
                            'col_3' => '12.klassi kursused',
                            'weight' => 1,
                        ),
                        'row_1' => array(
                            'col_0' => 'Eesti keel',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 2,
                        ),
                        'row_2' => array(
                            'col_0' => 'Kirjandus',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 3,
                        ),
                        'row_3' => array(
                            'col_0' => 'B2 taseme võõrkeel	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 4,
                        ),
                        'row_4' => array(
                            'col_0' => 'B1 taseme võõrkeel	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 5,
                        ),
                        'row_5' => array(
                            'col_0' => 'Matemaatika	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 6,
                        ),
                        'row_6' => array(
                            'col_0' => 'Geograafia	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 7,
                        ),
                        'row_7' => array(
                            'col_0' => 'Bioloogia	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 8,
                        ),
                        'row_8' => array(
                            'col_0' => 'Keemia	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 9,
                        ),
                        'row_9' => array(
                            'col_0' => 'Füüsika	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 10,
                        ),
                        'row_10' => array(
                            'col_0' => 'Ajalugu	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 11,
                        ),
                        'row_11' => array(
                            'col_0' => 'Ühiskonnaõpetus	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 12,
                        ),
                        'row_12' => array(
                            'col_0' => 'Inimeseõpetus	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 13,
                        ),
                        'row_13' => array(
                            'col_0' => 'Muusikaõpetus	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 14,
                        ),
                        'row_14' => array(
                            'col_0' => 'Kunstiõpetus	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 15,
                        ),
                        'row_15' => array(
                            'col_0' => 'Kehaline kasvatus	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 16,
                        ),
                        'row_16' => array(
                            'col_0' => 'Uurimistöö	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 17,
                        ),
                        'row_17' => array(
                            'col_0' => 'Arvutiõpetus	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 18,
                        ),
                        'row_18' => array(
                            'col_0' => 'Valikkursus	',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 19,
                        ),
                        'row_19' => array(
                            'col_0' => 'Kokku',
                            'col_1' => '',
                            'col_2' => '',
                            'col_3' => '',
                            'weight' => 20,
                        ),
                    ),
                ),
            ),
        ),
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'tablefield',
                'settings' => array(
                    'export_csv' => false,
                    'header_orientation' => 'Horizontal',
                    'hide_cols_skip_head' => false,
                    'hide_empty_cols' => false,
                    'hide_empty_rows' => false,
                    'hide_header' => false,
                    'sortable' => false,
                    'sticky_header' => true,
                    'striping' => true,
                    'trim_trailing_cols' => false,
                    'trim_trailing_rows' => false,
                ),
                'type' => 'tablefield_default',
                'weight' => 22,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_subjects_table',
        'label' => 'Õppeainete tabel',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'tablefield',
            'settings' => array(
                'cell_processing' => 0,
                'data_sources' => array(
                    'paste' => 'paste',
                    'upload' => 'upload',
                ),
                'input_type' => 'textfield',
                'lock_values' => 1,
                'max_length' => 2048,
                'restrict_rebuild' => 0,
            ),
            'type' => 'tablefield',
            'weight' => 15,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_table_description'.
    $field_instances['node-curriculum-field_table_description'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 29,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_table_description',
        'label' => 'Table description',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 14,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_table_descriptions'.
    $field_instances['node-curriculum-field_table_descriptions'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'paragraphs',
                'settings' => array(
                    'view_mode' => 'full',
                ),
                'type' => 'paragraphs_view',
                'weight' => 25,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_table_descriptions',
        'label' => 'Tabeli veeru/rea juhendav abitekst',
        'required' => 0,
        'settings' => array(
            'add_mode' => 'button',
            'allowed_bundles' => array(
                'catering_food_by_day' => -1,
                'contacts' => -1,
                'contacts_department' => -1,
                'description' => 'description',
                'jobs' => -1,
                'reception_time' => -1,
                'subpage' => -1,
                'table' => -1,
            ),
            'bundle_weights' => array(
                'catering_food_by_day' => 10,
                'contacts' => 2,
                'contacts_department' => 3,
                'description' => 4,
                'jobs' => 5,
                'reception_time' => 6,
                'subpage' => 7,
                'table' => 8,
            ),
            'default_edit_mode' => 'preview',
            'entity_translation_sync' => false,
            'title' => 'kirjeldus',
            'title_multiple' => 'kirjeldus',
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 0,
            'module' => 'paragraphs',
            'settings' => array(),
            'type' => 'paragraphs_embed',
            'weight' => 17,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_target_group'.
    $field_instances['node-curriculum-field_target_group'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'text',
                'settings' => array(),
                'type' => 'text_default',
                'weight' => 16,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_target_group',
        'label' => 'Target group',
        'required' => 0,
        'settings' => array(
            'entity_translation_sync' => false,
            'text_processing' => 0,
            'user_register_form' => false,
        ),
        'widget' => array(
            'active' => 1,
            'module' => 'text',
            'settings' => array(
                'size' => 60,
            ),
            'type' => 'text_textfield',
            'weight' => 10,
        ),
    );

    // Exported field_instance: 'node-curriculum-field_textbooks'.
    $field_instances['node-curriculum-field_textbooks'] = array(
        'bundle' => 'curriculum',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'link',
                'settings' => array(),
                'type' => 'link_default',
                'weight' => 30,
            ),
            'teaser' => array(
                'label' => 'above',
                'settings' => array(),
                'type' => 'hidden',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'node',
        'field_name' => 'field_textbooks',
        'label' => 'Materials',
        'required' => 0,
        'settings' => array(
            'absolute_url' => 1,
            'attributes' => array(
                'class' => '',
                'configurable_class' => 0,
                'configurable_title' => 0,
                'rel' => '',
                'target' => 'default',
                'title' => '',
            ),
            'display' => array(
                'url_cutoff' => 80,
            ),
            'enable_tokens' => 1,
            'entity_translation_sync' => false,
            'rel_remove' => 'default',
            'title' => 'optional',
            'title_label_use_field_label' => 0,
            'title_maxlength' => 128,
            'title_value' => '',
            'url' => 0,
            'user_register_form' => false,
            'validate_url' => 1,
        ),
        'widget' => array(
            'active' => 0,
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_field',
            'weight' => 20,
        ),
    );

    // Translatables
    // Included for use with string extractors like potx.
    t('Assessment');
    t('Attachments');
    t('Days it takes place');
    t('Description');
    t('Erialade tabel');
    t('Field');
    t('Instructor');
    t('Jobs pretext');
    t('Kontaktid');
    t('Length');
    t('Materials');
    t('Pictures');
    t('Premise');
    t('Rating');
    t('Room');
    t('Start ');
    t('Tabbed content page type');
    t('Tabeli veeru/rea juhendav abitekst');
    t('Table description');
    t('Table title');
    t('Target group');
    t('Töökohad');
    t('Õppeainete tabel');

    return $field_instances;
}
function hitsa_curriculum_delete_custom_node_fields()
{
    foreach (array_keys(_hitsa_curriculum_installed_node_fields()) as $field) {
        $fieldd = field_info_field($field);
        if (!empty($fieldd)) {
            if (!empty($fieldd['bundles'])) {
                if (!empty($fieldd['bundles']['node'])) {
                    if (count($fieldd['bundles']['node']) > 1) {

                    } elseif (count($fieldd['bundles']['node']) == 1) {
//                        field_delete_field($fieldd['field_name']);
                    }
                }
            }
        } else {
//            field_delete_field($field);
        }
    }
    $instances = field_info_instances('node', 'curriculum');
    foreach ($instances as $instance_name => $field_instance) {
        field_delete_instance($field_instance);
    }
}
function hitsa_curriculum_make_fields_conditional()
{
    foreach (_hitsa_curriculum_conditional_fields() as $conditional) {
        $ids = _hitsa_curriculum_get_field_ids($conditional['dependee'], $conditional['dependent']);
        conditional_fields_dependency_insert($ids['dependee'], $ids['dependent'], $conditional['options']);
    }
}
function _hitsa_curriculum_conditional_fields()
{

    $items = array();

    $items["node:curriculum:0"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_assessment',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'hobby-groups',
                3 => 'e-course',
                4 => 'hobby-activity',
                5 => 'ordered-trainings',
                6 => 'elective-courses',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:1"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_attachments',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'hobby-groups',
                3 => 'ordered-trainings',
                4 => 'e-course',
                5 => 'hobby-activity',
                6 => 'elective-courses',
                7 => 'specialities',
                8 => 'subject-field'
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:2"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_curriculum_length',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'hobby-groups',
                3 => 'ordered-trainings',
                4 => 'e-course',
                5 => 'hobby-activity',
                6 => 'elective-courses',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:3"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_curriculum_start',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'ordered-trainings',
                3 => 'hobby-groups',
                4 => 'e-course',
                5 => 'hobby-activity',
                6 => 'elective-courses',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:4"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_days_place',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'ordered-trainings',
                3 => 'hobby-groups',
                4 => 'e-course',
                5 => 'hobby-activity',
                6 => 'elective-courses',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:5"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_field',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                4 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                4 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 1,
            'value_form' => 'specialities',
            'value' => array(
                0 => array(
                    'value' => 'specialities',
                ),
            ),
            'values' => array(),
        ),
    );

    $items["node:curriculum:6"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_instructor',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'hobby-groups',
                3 => 'e-course',
                4 => 'ordered-trainings',
                5 => 'hobby-activity',
                6 => 'elective-courses',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:7"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_jobs',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                4 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                4 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 1,
            'value_form' => 'specialities',
            'value' => array(
                0 => array(
                    'value' => 'specialities',
                ),
            ),
            'values' => array(),
        ),
    );

    $items["node:curriculum:8"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_jobs_pretext',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                4 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                4 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 1,
            'value_form' => 'specialities',
            'value' => array(
                0 => array(
                    'value' => 'specialities',
                ),
            ),
            'values' => array(),
        ),
    );

    $items["node:curriculum:9"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_premise',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'hobby-groups',
                3 => 'e-course',
                4 => 'ordered-trainings',
                5 => 'hobby-activity',
                6 => 'elective-courses',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:10"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_rating',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'hobby-groups',
                3 => 'e-course',
                4 => 'hobby-activity',
                5 => 'elective-courses',
                6 => 'ordered-trainings',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:11"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_room',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'hobby-groups',
                3 => 'e-course',
                4 => 'ordered-trainings',
                5 => 'hobby-activity',
                6 => 'elective-courses',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:12"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_short_description',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                7 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                8 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                7 => array(
                    1 => 1,
                    3 => 0,
                ),
                8 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'subject-field',
                1 => 'specialities',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:13"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_specialitiy_table',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                4 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                4 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 1,
            'value_form' => 'specialities',
            'value' => array(
                0 => array(
                    'value' => 'specialities',
                ),
            ),
            'values' => array(),
        ),
    );

    $items["node:curriculum:14"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_subjects_table',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                4 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                4 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 1,
            'value_form' => 'subject-field',
            'value' => array(
                0 => array(
                    'value' => 'subject-field',
                ),
            ),
            'values' => array(),
        ),
    );

    $items["node:curriculum:15"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_table_description',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                4 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                4 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'subject-field',
                1 => 'specialities',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:16"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_table_descriptions',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                4 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                4 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'specialities',
                1 => 'subject-field',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:17"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_target_group',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'hobby-groups',
                3 => 'ordered-trainings',
                4 => 'e-course',
                5 => 'hobby-activity',
                6 => 'elective-courses',
            ),
            'value' => array(),
        ),
    );

    $items["node:curriculum:18"] = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_textbooks',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'hobby-groups',
                3 => 'ordered-trainings',
                4 => 'e-course',
                5 => 'hobby-activity',
                6 => 'elective-courses',
            ),
            'value' => array(),
        ),
    );

    return $items;

}
function _hitsa_curriculum_get_field_ids($dependee, $dependent)
{
    $ids = array();
    $field = field_info_instance('node', $dependee, 'curriculum');

    $field2 = field_info_instance('node', $dependent, 'curriculum');

    $ids = array(
        'dependee' => $field['id'],
        'dependent' => $field2['id'],
    );
    return $ids;
}


function hitsa_curriculum_add_custom_taxonomy_fields()
{
    foreach (hitsa_curriculum_add_custom_taxonomy_fields_base() as $field) {
        field_create_field($field);
    }
    foreach (hitsa_curriculum_add_custom_taxonomy_fields_instances() as $field_instance) {
        field_create_instance($field_instance);
    }
}
function hitsa_curriculum_add_custom_taxonomy_fields_base()
{
    $field_bases = array();

    // Exported field_base: 'field_icon_choice'.

    $field_bases['field_icon_choice'] = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => 'field_icon_choice',
        'indexes' => array(
            'value' => array(
                0 => 'value',
            ),
        ),
        'locked' => 0,
        'module' => 'list',
        'settings' => array(
            'allowed_values' => array(
                'areas-aiandus' => 'Aiandus',
                'areas-arhitektuur' => 'Arhitektuur',
                'areas-ariteenindus' => 'Ariteenindus',
                'areas-disain' => 'Disain',
                'areas-ehitus' => 'Ehitus',
                'areas-elektrienergia' => 'Elektrienergia',
                'areas-iluteenindus' => 'Iluteenindus',
                'areas-info' => 'Info',
                'areas-kaevandamine' => 'Kaevandamine',
                'areas-kalandus' => 'Kalandus',
                'areas-kasitoo' => 'Kasitoo',
                'areas-kaubandus' => 'Kaubandus',
                'areas-keemiatehnoloogia' => 'Keemiatehnoloogia',
                'areas-keskkonnakaitse' => 'Keskkonnakaitse',
                'areas-laevandus' => 'Laevandus',
                'areas-lastehoid' => 'Lastehoid',
                'areas-materjalid' => 'Materjalid',
                'areas-mehaanika' => 'Mehaanika',
                'areas-metsandus' => 'Metsandus',
                'areas-muusika' => 'Muusika',
                'areas-pollumajandus' => 'Pollumajandus',
                'areas-puitmaterjalid' => 'Puitmaterjalid',
                'areas-sojandus' => 'Sojandus',
                'areas-tekstiil' => 'Tekstiil',
                'areas-tervishoid' => 'Tervishoid',
                'areas-toiduained' => 'Toiduained',
                'areas-transporditeenused' => 'Transporditeenused',
                'areas-transporditehnika' => 'Transporditehnika',
                'areas-turism' => 'Turism',
                'areas-vara_isikukaitse' => 'Vara_isikukaitse',
                'areas-veterinaaria' => 'Veterinaaria',
            ),
            'allowed_values_function' => '',
            'entity_translation_sync' => false,
        ),
        'translatable' => 0,
        'type' => 'list_text',
    );

    return $field_bases;
}
function hitsa_curriculum_add_custom_taxonomy_fields_instances()
{
    $field_instances = array();

    // Exported field_instance: 'taxonomy_term-fields-field_icon_choice'.
    $field_instances['taxonomy_term-fields-field_icon_choice'] = array(
        'bundle' => 'fields',
        'default_value' => null,
        'deleted' => 0,
        'description' => '',
        'display' => array(
            'default' => array(
                'label' => 'above',
                'module' => 'list',
                'settings' => array(),
                'type' => 'list_default',
                'weight' => 0,
            ),
        ),
        'entity_type' => 'taxonomy_term',
        'field_name' => 'field_icon_choice',
        'label' => 'Icon choice',
        'required' => true,
        'settings' => array(
            'entity_translation_sync' => false,
            'user_register_form' => false,
        ),
        'widget' => array(
            'module' => 'options',
            'settings' => array(),
            'type' => 'options_select',
            'weight' => 1,
        ),
    );

    // Translatables
    // Included for use with string extractors like potx.
    t('Field picture');
    t('Icon choice');


    return $field_instances;
}
function hitsa_curriculum_update_7000(){
    $dependencies = conditional_fields_load_dependencies('node','curriculum');
    $id=null;
    if(!empty($dependencies['dependents']['field_attachments'])){
        foreach ($dependencies['dependents']['field_attachments'] as $dep_key => $dep_value) {
            $id = $dep_key;
            break;
        }
    }
    $dependecy = array(
        'entity' => 'node',
        'bundle' => 'curriculum',
        'dependent' => 'field_attachments',
        'dependee' => 'field_school_selections',
        'options' => array(
            'state' => 'visible',
            'condition' => 'value',
            'grouping' => 'AND',
            'effect' => 'show',
            'effect_options' => array(),
            'element_view' => array(
                1 => 1,
                2 => 2,
                5 => 0,
                3 => 0,
                4 => 0,
            ),
            'element_view_per_role' => 0,
            'element_view_roles' => array(
                1 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                2 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                3 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                9 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
                10 => array(
                    1 => 1,
                    2 => 2,
                    5 => 0,
                    3 => 0,
                    4 => 0,
                ),
            ),
            'element_edit' => array(
                1 => 1,
                3 => 0,
            ),
            'element_edit_per_role' => 0,
            'element_edit_roles' => array(
                1 => array(
                    1 => 1,
                    3 => 0,
                ),
                2 => array(
                    1 => 1,
                    3 => 0,
                ),
                3 => array(
                    1 => 1,
                    3 => 0,
                ),
                9 => array(
                    1 => 1,
                    3 => 0,
                ),
                10 => array(
                    1 => 1,
                    3 => 0,
                ),
            ),
            'selector' => '',
            'values_set' => 3,
            'value_form' => '_none',
            'values' => array(
                0 => 'elective-subjects',
                1 => 'preparatory-courses',
                2 => 'hobby-groups',
                3 => 'ordered-trainings',
                4 => 'e-course',
                5 => 'hobby-activity',
                6 => 'elective-courses',
                7 => 'specialities',
                8 => 'subject-field'
            ),
            'value' => array(),
        ),
    );
    $dependee = field_info_instance('node', $dependecy['dependee'], 'curriculum')['id'];
    $dependent = field_info_instance('node', $dependecy['dependent'], 'curriculum')['id'];
    $dependency = array(
        'id' => $id,
        'dependee'  => $dependee,
        'dependent' => $dependent,
        'options'   => $dependecy['options'],
    );
    conditional_fields_dependency_update($dependency);
}
function hitsa_curriculum_update_7001(){
    $field_instance =  field_info_instance('node','field_pictures','curriculum');
  if(empty($field_instance['widget']['settings']['browser_plugins'])){
    $field_instance['widget']['settings']['browser_plugins']['media_internet']=0;
    field_update_instance($field_instance);
  }
}
function hitsa_curriculum_update_7002(){
    $field_instance =  field_info_instance('node','field_pictures','curriculum');
  if(!empty($field_instance['widget']['settings']['browser_plugins'])){
    $field_instance['widget']['settings']['browser_plugins']['media_internet']=0;
    field_update_instance($field_instance);
  }
}
function hitsa_curriculum_update_7003(){
    $field_instance =  field_info_instance('node','field_pictures','curriculum');
    if(!empty($field_instance['widget']['settings']['browser_plugins'])){
      $field_instance['widget']['settings']['browser_plugins']['media_internet']=0;
    }
    field_update_instance($field_instance);
}
function hitsa_curriculum_update_7004(){
    $field_instance =  field_info_instance('node','field_pictures','curriculum');
    if(!empty($field_instance['widget']['settings']['browser_plugins'])){
      $field_instance['widget']['settings']['browser_plugins']['media_internet']=0;
    }
    field_update_instance($field_instance);
}
function hitsa_curriculum_update_7005(){
    $field_instance =  array(
      'bundle' => 'curriculum',
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'image',
          'settings' => array(
            'image_link' => '',
            'image_style' => '',
          ),
          'type' => 'image',
          'weight' => 4,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_pictures',
      'label' => 'Pictures',
      'required' => 0,
      'settings' => array(
        'alt_field' => 0,
        'default_image' => 0,
        'entity_translation_sync' => FALSE,
        'file_directory' => 'curriculum_pictures',
        'file_extensions' => 'png gif jpg jpeg',
        'max_filesize' => '',
        'max_resolution' => '',
        'min_resolution' => '',
        'title_field' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'media',
        'settings' => array(
          'allowed_schemes' => array(
            'public' => 'public',
            'youtube' => 0,
          ),
          'allowed_types' => array(
            'audio' => 0,
            'document' => 0,
            'image' => 'image',
            'video' => 0,
          ),
          'browser_plugins' => array(
            'media_default--media_browser_1' => 'media_default--media_browser_1',
            'media_default--media_browser_my_files' => 'media_default--media_browser_my_files',
            'media_internet' => 0,
            'upload' => 'upload',
          ),
          'manualcrop_crop_info' => 1,
          'manualcrop_default_crop_area' => 1,
          'manualcrop_enable' => 0,
          'manualcrop_inline_crop' => 0,
          'manualcrop_instant_crop' => FALSE,
          'manualcrop_instant_preview' => 1,
          'manualcrop_keyboard' => 1,
          'manualcrop_maximize_default_crop_area' => 0,
          'manualcrop_require_cropping' => array(),
          'manualcrop_styles_list' => array(),
          'manualcrop_styles_mode' => 'include',
          'manualcrop_thumblist' => 0,
        ),
        'type' => 'media_generic',
        'weight' => 23,
      ),
    );
    field_update_instance($field_instance);
}
